include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/colors.ini

[colors]
background = #1A374D
background-alt = #1A374D
foreground = #C5C8C6
primary = #F0C674
secondary = #9088D4
alert = #A54242
disabled = #707880

[bar/example]
background = ${colors.background}
foreground = ${colors.foreground}

margin-bottom = 0

monitor = ${env:MONITOR:}
width = 100%
height = 24pt
radius = 6

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

fixed-center = true
font-0 = MesloLGLDZ NF:style=Regular:size=12;4
font-1 = Hack Nerd Font:size=15;2
font-2 = Hack Nerd Font:size=15;2
font-3 = MesloLGLDZ NF:style=Regular:size=18;4
font-4 = Hack Nerd Font:size=18;2
font-5 = Hack Nerd Font:size=20;2

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

;;;;;; Module Positioning
modules-left = herbstluftwm
modules-center = xwindow
modules-right = date

# Tray Settings
tray-position = right
tray-padding = 5
tray-background = ${colors.background-alt}
tray-maxsize = 26
# tray-detached = false

[settings]
screenchange-reload = true
pseudo-transparency = false
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false [global/wm] margin-top = 5 margin-bottom = 5 vim:set ft=dosini:

